require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'lib/tasks/auto_annotate_models.rake'
    # bundled gems
    - vendor/**/*
    # testing gems
    - testing/vendor/**/*

Layout/LineLength:
  Max: 105

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/api/v1/slides_controller.rb'

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Metrics/MethodLength:
  Max: 15

Lint/DuplicateBranch:
  Exclude:
    - app/controllers/concerns/authenticable.rb

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Exclude:
    - 'app/controllers/api/v1/testimonials_controller.rb'

MultipleExpectations:
  Exclude:
    - spec/**/*

MultipleMemoizedHelpers:
  Exclude:
    - spec/**/*
